ktor:
    application:
        modules:
            - com.newmotion.ApplicationKt.module
    deployment:
        port: 8080
        host: 0.0.0.0

database:
    url: "jdbc:postgresql://localhost:5432/truepal_db"
    driver: "org.postgresql.Driver"
    user: "truepal"
    password: "hrisgood"
    maxPoolSize: 10
    minIdleConnections: 2